### ISSUE TITLE
yaml format

### ISSUE THREAD

**Issue by DjordjeVucinac82** [DjordjeVucinac82/DjordjeVucinac82#1]
```yaml
apiVersion: v
kind: Human
metadata:
  name: 
spec:
  purpose: Help others learn container DevOps
  
  locations:
    - 
      type: YouTube Live Stream on Thursdays
      where: 
    - 
      type: Homepage
      where: 
    - 
      type: Discord Server
      where: 
    -
      type: Podcast
      where: 

  favorites:
    number: 
    animal: 🐶
    emoji: 🤦
    food: 🥩
```
